### ISSUE TITLE
Does not compile: "invalid use of incomplete type ‘class Ui::Lua4RSConfig"

### ISSUE THREAD

**Issue by UMLAUTaxl** [sehraf/Lua4RS#6]
After solving a lot of linking problems and replacing _ui_Lua4RSConfig.h_ (which is nowhere to be found) with _gui/Lua4RSConfig.h_ in gui/Lua4RSConfig.cpp I got this:
```
$ make
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o Lua4RSConfig.o gui/Lua4RSConfig.cpp
gui/Lua4RSConfig.cpp: In constructor ‘Lua4RSConfig::Lua4RSConfig(QWidget*)’:
gui/Lua4RSConfig.cpp:9:16: error: invalid use of incomplete type ‘class Ui::Lua4RSConfig’
     ui(new Ui::Lua4RSConfig)
                ^~~~~~~~~~~~
In file included from gui/Lua4RSConfig.cpp:3:
./gui/Lua4RSConfig.h:9:7: note: forward declaration of ‘class Ui::Lua4RSConfig’
 class Lua4RSConfig;
       ^~~~~~~~~~~~
gui/Lua4RSConfig.cpp:11:7: error: invalid use of incomplete type ‘class Ui::Lua4RSConfig’
     ui->setupUi(this);
       ^~
In file included from gui/Lua4RSConfig.cpp:3:
./gui/Lua4RSConfig.h:9:7: note: forward declaration of ‘class Ui::Lua4RSConfig’
 class Lua4RSConfig;
       ^~~~~~~~~~~~
gui/Lua4RSConfig.cpp:13:15: error: invalid use of incomplete type ‘class Ui::Lua4RSConfig’
     connect(ui->sb_starupEvent, SIGNAL(valueChanged(int)), this, SLOT(startUpChanged(int)));
               ^~
In file included from gui/Lua4RSConfig.cpp:3:
./gui/Lua4RSConfig.h:9:7: note: forward declaration of ‘class Ui::Lua4RSConfig’
 class Lua4RSConfig;
       ^~~~~~~~~~~~
gui/Lua4RSConfig.cpp:14:15: error: invalid use of incomplete type ‘class Ui::Lua4RSConfig’
     connect(ui->sb_tickInterval, SIGNAL(valueChanged(int)), this, SLOT(tickIntervalChanged(int)));
               ^~
In file included from gui/Lua4RSConfig.cpp:3:
./gui/Lua4RSConfig.h:9:7: note: forward declaration of ‘class Ui::Lua4RSConfig’
 class Lua4RSConfig;
       ^~~~~~~~~~~~
gui/Lua4RSConfig.cpp: In destructor ‘virtual Lua4RSConfig::~Lua4RSConfig()’:
gui/Lua4RSConfig.cpp:19:12: warning: possible problem detected in invocation of delete operator: [-Wdelete-incomplete]
     delete ui;
            ^~
gui/Lua4RSConfig.cpp:19:12: warning: invalid use of incomplete type ‘class Ui::Lua4RSConfig’
In file included from gui/Lua4RSConfig.cpp:3:
./gui/Lua4RSConfig.h:9:7: note: forward declaration of ‘class Ui::Lua4RSConfig’
 class Lua4RSConfig;
       ^~~~~~~~~~~~
gui/Lua4RSConfig.cpp:19:12: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
     delete ui;
            ^~
gui/Lua4RSConfig.cpp: In member function ‘virtual void Lua4RSConfig::load()’:
gui/Lua4RSConfig.cpp:24:21: error: invalid use of incomplete type ‘class Ui::Lua4RSConfig’
     whileBlocking(ui->sb_starupEvent)->setValue(L4R::L4RConfig->getSecondsToStarUpEvent());
                     ^~
In file included from gui/Lua4RSConfig.cpp:3:
./gui/Lua4RSConfig.h:9:7: note: forward declaration of ‘class Ui::Lua4RSConfig’
 class Lua4RSConfig;
       ^~~~~~~~~~~~
gui/Lua4RSConfig.cpp:25:21: error: invalid use of incomplete type ‘class Ui::Lua4RSConfig’
     whileBlocking(ui->sb_tickInterval)->setValue(L4R::L4RConfig->getTickIntervalInSeconds());
                     ^~
In file included from gui/Lua4RSConfig.cpp:3:
./gui/Lua4RSConfig.h:9:7: note: forward declaration of ‘class Ui::Lua4RSConfig’
 class Lua4RSConfig;
       ^~~~~~~~~~~~
gui/Lua4RSConfig.cpp: In member function ‘virtual bool Lua4RSConfig::save(QString&)’:
gui/Lua4RSConfig.cpp:30:47: error: invalid use of incomplete type ‘class Ui::Lua4RSConfig’
     L4R::L4RConfig->setSecondsToStarUpEvent(ui->sb_starupEvent->value());
                                               ^~
In file included from gui/Lua4RSConfig.cpp:3:
./gui/Lua4RSConfig.h:9:7: note: forward declaration of ‘class Ui::Lua4RSConfig’
 class Lua4RSConfig;
       ^~~~~~~~~~~~
gui/Lua4RSConfig.cpp:31:48: error: invalid use of incomplete type ‘class Ui::Lua4RSConfig’
     L4R::L4RConfig->setTickIntervalInSeconds(ui->sb_tickInterval->value());
                                                ^~
In file included from gui/Lua4RSConfig.cpp:3:
./gui/Lua4RSConfig.h:9:7: note: forward declaration of ‘class Ui::Lua4RSConfig’
 class Lua4RSConfig;
       ^~~~~~~~~~~~
gui/Lua4RSConfig.cpp: In member function ‘void Lua4RSConfig::startUpChanged(int)’:
gui/Lua4RSConfig.cpp:37:47: error: invalid use of incomplete type ‘class Ui::Lua4RSConfig’
     L4R::L4RConfig->setSecondsToStarUpEvent(ui->sb_starupEvent->value());
                                               ^~
In file included from gui/Lua4RSConfig.cpp:3:
./gui/Lua4RSConfig.h:9:7: note: forward declaration of ‘class Ui::Lua4RSConfig’
 class Lua4RSConfig;
       ^~~~~~~~~~~~
gui/Lua4RSConfig.cpp: In member function ‘void Lua4RSConfig::tickIntervalChanged(int)’:
gui/Lua4RSConfig.cpp:42:48: error: invalid use of incomplete type ‘class Ui::Lua4RSConfig’
     L4R::L4RConfig->setTickIntervalInSeconds(ui->sb_tickInterval->value());
                                                ^~
In file included from gui/Lua4RSConfig.cpp:3:
./gui/Lua4RSConfig.h:9:7: note: forward declaration of ‘class Ui::Lua4RSConfig’
 class Lua4RSConfig;
       ^~~~~~~~~~~~
make: *** [Makefile:507: Lua4RSConfig.o] Error 1
```

**Comment by sehraf** [comment]
Can you give the latest commit a try? Compile tested (without any further changes)

**Comment by UMLAUTaxl** [comment]
Well, I had to download Tencent/rapidjson and put a symlink into Lua4RS. But aside from that it compiled okay.

Unfortunately for that I had to clone into the current RS source. I guess that's why the plugin isn't working with version 0.6.9999 downloaded from here http://download.opensuse.org/repositories/network:/retroshare/Debian_10/

**Comment by sehraf** [comment]
As far as i know, you always need the source to build plugins. And you need the same code basis for RS and plugins - mixing may work but is not considered supported. Usually the ones who provide compiled versions of RS also provide the corresponding plugins.

As it was pointed out in the forum, the new json API is the way to go. Thus, Lua4RS is only maintained and not active developed anymore.
Have a look here https://github.com/sehraf/python-retroshare

May i close this issue?

**Comment by UMLAUTaxl** [comment]
Thank you.
Yes, close it.
